apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: todoapp
  labels:
    app: todoapp-daemonset
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: curlimages/curl:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                curl http://todoapp-service.todoapp.svc.cluster.local:80
                sleep 300
              done 

  